name: compassx_example
description: "Demonstrates how to use the compassx plugin."
version: 0.0.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  compassx:
    path: ../
    version: 0.0.2
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
